name = "the-relay-susu"                # todo
main = "index.js"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[ai]
binding = "AI" # i.e. available in your Worker on env.AI

[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "openai-cf-images"
preview_bucket_name = "ai-images"

[vars]
CLOUDFLARE_ACCOUNT_ID = "TODO" # replace with your own.
CLOUDFLARE_API_TOKEN = "TODO"
ACCESS_TOKEN = "TODO"
# MODEL_MAPPER = { "gpt-3.5-turbo" = "@cf/meta/llama-2-7b-chat-int8" } # Optional

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.